stages:
  - build
  - deploy

jupyter-build:
  stage: build
  tags:
    - cpu
  image: python:slim
  before_script:
    # - python -m pip install --upgrade pip
    # - pip install -r requirements.txt
    # - pip install .
    - pip install -r docs/requirements-docs.txt
    # - pip install myst-parser
  script:
    - pip install -U jupyter-book
    - jupyter-book clean docs
    - jupyter-book build docs
  artifacts:
    paths:
      - docs/_build/

pages:
  stage: deploy
  tags:
    - cpu
  image: busybox:latest
  script:
    - mv docs/_build/html docs/public
  artifacts:
    paths:
      - docs/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH