#!/usr/bin/env python
"""
Text user interface for the DTaaS service

!!! WIP !!!

Author: @lbabetto
"""

import os
import subprocess
from core.db import show_db_details

import logging

logger = logging.getLogger(__name__)


print("  ┌─────────────────────────────────────────────────┐")
print("  │ Digital Twin as a Service - Text User Interface │")
print("  └─────────────────────────────────────────────────┘")

print("  - Retrieving database information")
print("  - Available databases:")

# Temporary, will need to be replaced with chain user and relative home directory
SUBMIT_DIR = "/home/centos/TESTS/2-tui"
