#!/usr/bin/env python
"""
Text user interface for the DTaaS service

!!! WIP !!!

Author: @lbabetto
"""

from tui.core.db import MONGODB_URI
from tui.core.hpc import launch_job
from tui.core.utils import read_cl, generate_file_list, print_info, FILE_LIST
from pymongo import MongoClient

USER = "user"
PASSWORD = "passwd"
IP = "localhost"
PORT = "27017"

MONGODB_URI = f"mongodb://{USER}:{PASSWORD}@{IP}:{PORT}/"

client = MongoClient(MONGODB_URI)

flags = read_cl()
generate_file_list(client=client, flags=flags)

if flags["info"]:
    print_info(client=client, flags=flags)

if flags["script"]:
    launch_job(flags["script"], FILE_LIST)
